CREATE TABLE drivers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  phone TEXT DEFAULT '',
  truck TEXT DEFAULT '',
  created_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE loads (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  load_number TEXT NOT NULL,
  load_type TEXT NOT NULL DEFAULT 'load' CHECK (load_type IN ('load', 'loadout')),
  driver_id INTEGER NOT NULL REFERENCES drivers(id),
  pickup_city TEXT NOT NULL,
  delivery_city TEXT NOT NULL,
  pickup_date TEXT NOT NULL,
  delivery_date TEXT NOT NULL,
  rate_amount DOUBLE PRECISION NOT NULL CHECK (rate_amount >= 0 AND rate_amount < 'Infinity'::DOUBLE PRECISION),
  status TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'picked_up', 'unloaded', 'invoiced', 'paid')),
  invoice_due_date TEXT NOT NULL DEFAULT '',
  archived_at TEXT DEFAULT NULL,
  folder_ref TEXT DEFAULT '',
  notes TEXT DEFAULT '',
  created_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (load_number, load_type)
);

CREATE TABLE files (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  load_id INTEGER NOT NULL REFERENCES loads(id) ON DELETE CASCADE,
  category TEXT NOT NULL CHECK (category IN ('rate_confirmation', 'updated_rate_confirmation', 'bol', 'lumper_receipt', 'invoice', 'other')),
  filename TEXT NOT NULL,
  storage_ref TEXT NOT NULL,
  web_link TEXT DEFAULT '',
  size DOUBLE PRECISION DEFAULT 0 CHECK (size >= 0 AND size <= 9007199254740991 AND size = trunc(size)),
  uploaded_at TEXT NOT NULL DEFAULT to_char(timezone('UTC', now()), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX loads_driver_archive ON loads(driver_id, archived_at);
CREATE INDEX files_load_id ON files(load_id);
CREATE UNIQUE INDEX files_storage_ref_unique ON files(storage_ref) WHERE storage_ref <> '';

CREATE TABLE dispatch_meta (
  singleton BOOLEAN PRIMARY KEY CHECK (singleton),
  schema_version INTEGER NOT NULL,
  storage_mode TEXT NOT NULL CHECK (storage_mode IN ('local', 'drive')),
  storage_root TEXT NOT NULL CHECK (storage_root <> '')
);

CREATE TABLE sync_runs (
  id UUID PRIMARY KEY,
  state JSONB NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
